# Generated by Django 6.1 on 2026-08-14 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
