# Generated by Django 6.1 on 2026-08-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_appointment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'Customer Enquiry', 'verbose_name_plural': 'Customer Enquiries'},
        ),
    ]
